### ISSUE TITLE
Lat/long & location of Parkour Roots Classes

### ISSUE THREAD

**Issue by domfennell** [Playwaze/opendata#2]
Hi Rupert,

Hope you're well. Just what to check something about the data in your endpoint: _Parkour Generations - Parkour Roots Class_ sessions all appear to have the same `lat/lng` (points to The Serpentine in Hyde Park) and `location` (_London Outdoor Training Spots_). However, looking at http://parkourgenerations.com/?timetable=parkour-roots, I can see that the _Roots Classes_ have specific locations (Oval, Westbourne Park). Would it be possible to attribute the correct info for each individual _Roots Class_?

Very best,

Dom

**Comment by rujenner** [comment]
Hi Dom,

This is because Parkour Generations haven't supplied a valid location for these particular classes. They've just entered "London Outdoor Training Spots" for all of these particular sessions. We have a piece of work about to start to use Google Maps API on these location fields (at the moment just free text). Playwaze allows admins to create auto recurring sessions so they just keep repeating. If the locations differ week to week we then rely on them updating the location field as they go. 
I'm a little perplexed as to where it's getting Hyde Park co-ordinates from? We can certainly look into that. I'm around if you want to call.
