### ISSUE TITLE
Consider adopting the OpenActive Opportunity Model

### ISSUE THREAD

**Issue by RoastVeg** [Playwaze/opendata#6]
N.B. This query originates from [SportSuite](http://sportsuite.co.uk)

What consideration is there being undertaken to the possibility of converting Playwaze's open data to conform to the OpenActive Opportunity Model? We have specific clients of ours that would be very eager to incorporate the data hosted on Playwaze, but the lack of standards compliance makes it infeasible to do so in a reasonable timeframe.

**Comment by rujenner** [comment]
@RoastVeg Playwaze is compliant with OpenActive's latest spec of the Opportunity Model. We noted that Playwaze was not listed as compliant in OpenActive's status list. This was because we were still hosting the old spec's dataset (alongside the new one) and it was confusing things. We'll be resolving that in the next day or two (by removing the old one) so only our new compliant dataset will be available. Please do get in touch (rupertjenner@playwaze.com) if you'd like to discuss further.

**Comment by rujenner** [comment]
@RoastVeg Just to let you know we are back on the OpenActive compliant status list: https://status.openactive.io/

**Comment by nickevansuk** [comment]
Quick conformance note (sorry for not spotting earlier @rujenner, hopefully a quick fix!):

Currently `SessionSeries` is being treated as an `EventSeries` and `ScheduledSession` is being treated as an `Event`. Sorry if this has been covered by @thill-odi already, but this data should be in the form of `SessionSeries` and `ScheduledSession` to conform to the spec. `EventSeries` is intended for a generic grouping of events rather than a grouping representing a schedule ([ref](https://www.openactive.io/modelling-opportunity-data/#grouping-together-events-eventseries-)). The validator seems to be erroneously passing in this case, so apologies for that - this has now been resolved!

The best option would be to split the feed into `SessionSeries` and `ScheduledSession` feeds, as is common practice for this use case.

**Comment by charlieclarke5** [comment]
@JoshuaLevett i believe this has all been closed off. Can you confirm?

**Comment by JoshuaLevett** [comment]
We have changed the way we send open data to both correct this, and to accommodate the addition of virtual events.
As can be seen at our datasite [here](https://playwaze.com/OpenData/OpenActive) we have four feeds available.
[Events](https://playwaze.com/OpenData/Events), [SessionSeries](https://playwaze.com/OpenData/SessionSeries), [ScheduledSessions](https://playwaze.com/OpenData/ScheduledSessions), and [OnDemand](https://playwaze.com/OpenData/OnDemand) events.

@RoastVeg @rujenner @nickevansuk @charlieclarke5 for awareness
